name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: testthedocs/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{f8f905f47e664cbbd1e15a223a47b0e5b620e232}}
          BUILD_DIR: test/build/ # The folder, the action should deploy.
          BUILD_SCRIPT: yarn install && yarn build # The build script the action should run prior to deploying.
